#
# AcuRite battery monitoring
#
# This device only has two power state: `OK` (0) and `low` (1). If no signal is
# received we assume that the battery is dead.
#
# @see /rtl4332mqtt/rtl2mqtt.sh
#
# @link https://www.acurite.com/indoor-temperature-sensor-and-humidity-gauge.html
# @link https://home-assistant.io/components/mqtt/
#
- platform: mqtt
  name: Humidor AcuRite Power
  state_topic: "home/Acurite_tower_sensor/11846"
  unit_of_measurement: '%'
  value_template: >-
    {% set battery_low = value_json.battery_low | int %}

    {% if battery_low %}
      10
    {% else %}
      100
    {% endif %}

- platform: template
  sensors:
    humidor_multisensor_battery:
      friendly_name: Humidor Multisensor Battery
      unit_of_measurement: '%'
      value_template: >-
        {{ states('sensor.humidor_acurite_power') }}

      icon_template: >-
        {% set battery_level = states('sensor.humidor_acurite_power') | int(-1) %}

        {% if battery_level < 0 %}
          mdi:battery-unknown
        {% elif battery_level > 10 %}
          mdi:battery
        {% elif battery_level == 10 %}
          mdi:battery-alert
        {% else %}
          mdi:battery-outline
        {% endif %}


#
# Fully Browser kiosk battery monitoring
#
# Licensed application running in kiosk mode on an Acer B3-A40 Android tablet.
#
# @link https://github.com/daemondazz/homeassistant-displays
#
- platform: template
  sensors:
    kiosk_battery:
      friendly_name: Kiosk Battery
      unit_of_measurement: '%'
      value_template: >-
        {% set battery_level = state_attr('display.kiosk', 'battery_level') %}

        {% if battery_level != None %}
          {{ battery_level | round }}
        {% else %}
          unknown
        {% endif %}

      icon_template: >-
        {% set battery_level = state_attr('display.kiosk', 'battery_level') %}

        {% if battery_level != None %}
          {% set battery_round = (battery_level / 10) | int * 10 %}

          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-outline
          {% endif %}
        {% else %}
          mdi:battery-unknown
        {% endif %}


#
# Raspberry Pi undervoltage monitoring
#
# @link https://github.com/custom-components/sensor.rpi_power
# @link https://community.home-assistant.io/t/raspberry-pi-power-sensor-updated-2018-07-25/58155/
#
- platform: rpi_power
  text_state: false


#
# ZWave battery monitoring
#
# @link https://aeotec.com/z-wave-door-window-sensor
# @link https://aeotec.com/z-wave-sensor
#
- platform: template
  sensors:
    front_door_sensor_battery:
      friendly_name: Front Door Sensor Battery
      unit_of_measurement: '%'
      value_template: >-
        {% set battery_level = state_attr('zwave.front_door', 'battery_level') %}

        {% if battery_level != None %}
          {{ battery_level | round }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        {% set battery_level = state_attr('zwave.front_door', 'battery_level') %}

        {% if battery_level != None %}
          {% set battery_round = (battery_level / 10) | int * 10 %}

          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-outline
          {% endif %}
        {% else %}
          mdi:battery-unknown
        {% endif %}

    kitchen_leak_sensor_battery:
      friendly_name: Kitchen Leak Sensor Battery
      unit_of_measurement: '%'
      value_template: >-
        {% set battery_level = state_attr('zwave.kitchen_leak_sensor', 'battery_level') %}

        {% if battery_level != None %}
          {{ battery_level | round }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        {% set battery_level = state_attr('zwave.kitchen_leak_sensor', 'battery_level') %}

        {% if battery_level != None %}
          {% set battery_round = (battery_level / 10) | int * 10 %}

          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-outline
          {% endif %}
        {% else %}
          mdi:battery-unknown
        {% endif %}

    lounge_multisensor_battery:
      friendly_name: Lounge Multisensor Battery
      unit_of_measurement: '%'
      value_template: >-
        {% set battery_level = state_attr('zwave.lounge_multisensor', 'battery_level') %}

        {% if battery_level != None %}
          {{ battery_level | round }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        {% set battery_level = state_attr('zwave.lounge_multisensor', 'battery_level') %}

        {% if battery_level != None %}
          {% set battery_round = (battery_level / 10) | int * 10 %}

          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-outline
          {% endif %}
        {% else %}
          mdi:battery-unknown
        {% endif %}

    siren_monitor_battery:
      friendly_name: Siren Monitor Battery
      unit_of_measurement: '%'
      value_template: >-
        {% set battery_level = states('sensor.siren_monitor_power_management') | int(-1) %}

        {% if battery_level < 0 %}
          unknown
        {% elif battery_level == 0 %}
          100
        {% elif battery_level == 10 %}
          10
        {% elif battery_round == 11 %}
          5
        {% else %}
          0
        {% endif %}
      icon_template: >-
        {% set battery_level = states('sensor.siren_monitor_power_management') | int(-1) %}

        {% if battery_level < 0 %}
          mdi:battery-unknown
        {% elif battery_level == 0 %}
          mdi:battery
        {% elif battery_level == 10 %}
          mdi:battery-10
        {% elif battery_round == 11 %}
          mdi:battery-alert
        {% else %}
          mdi:battery-outline
        {% endif %}

    washroom_leak_sensor_battery:
      friendly_name: Washroom Leak Sensor Battery
      unit_of_measurement: '%'
      value_template: >-
        {% set battery_level = state_attr('zwave.washroom_leak_sensor', 'battery_level') %}

        {% if battery_level != None %}
          {{ battery_level | round }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        {% set battery_level = state_attr('zwave.washroom_leak_sensor', 'battery_level') %}

        {% if battery_level != None %}
          {% set battery_round = (battery_level / 10) | int * 10 %}

          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-outline
          {% endif %}
        {% else %}
          mdi:battery-unknown
        {% endif %}

    washroom_multisensor_battery:
      friendly_name: Washroom Multisensor Battery
      unit_of_measurement: '%'
      value_template: >-
        {% set battery_level = state_attr('zwave.washroom_multisensor', 'battery_level') %}

        {% if battery_level != None %}
          {{ battery_level | round }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        {% set battery_level = state_attr('zwave.washroom_multisensor', 'battery_level') %}

        {% if battery_level != None %}
          {% set battery_round = (battery_level / 10) | int * 10 %}

          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-outline
          {% endif %}
        {% else %}
          mdi:battery-unknown
        {% endif %}
